# Generated by Django 3.0 on 2020-08-23 11:34

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import main.utilites


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photologue', '0011_auto_20190223_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, verbose_name='Пункт Меню')),
                ('slug_title', models.SlugField(max_length=150, verbose_name='Коротка назва')),
                ('content_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Наповнення Сторінки')),
                ('image', models.ImageField(blank=True, upload_to=main.utilites.get_timestamp_path_article, verbose_name='Зображення')),
                ('video', models.FileField(blank=True, upload_to=main.utilites.get_timestamp_path_navmenu, verbose_name='Відео до статті не більше 10 Мб')),
                ('file_1', models.FileField(blank=True, upload_to=main.utilites.get_timestamp_path_navmenu, verbose_name='Додати файл 1')),
                ('file_2', models.FileField(blank=True, upload_to=main.utilites.get_timestamp_path_navmenu, verbose_name='Додати файл 2')),
                ('file_3', models.FileField(blank=True, upload_to=main.utilites.get_timestamp_path_navmenu, verbose_name='Додати файл 3')),
                ('file_4', models.FileField(blank=True, upload_to=main.utilites.get_timestamp_path_navmenu, verbose_name='Додати файл 4')),
                ('file_5', models.FileField(blank=True, upload_to=main.utilites.get_timestamp_path_navmenu, verbose_name='Додати файл 5')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='photologue.Gallery', verbose_name='Галерея статті')),
            ],
            options={
                'verbose_name': 'Стаття',
                'verbose_name_plural': 'Статті',
            },
        ),
    ]
