# Generated by Django 3.0 on 2020-08-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='title_file_1',
            field=models.TextField(blank=True, verbose_name='Назва файлу 1'),
        ),
        migrations.AddField(
            model_name='content',
            name='title_file_2',
            field=models.TextField(blank=True, verbose_name='Назва файлу 2'),
        ),
        migrations.AddField(
            model_name='content',
            name='title_file_3',
            field=models.TextField(blank=True, verbose_name='Назва файлу 3'),
        ),
        migrations.AddField(
            model_name='content',
            name='title_file_4',
            field=models.TextField(blank=True, verbose_name='Назва файлу 4'),
        ),
        migrations.AddField(
            model_name='content',
            name='title_file_5',
            field=models.TextField(blank=True, verbose_name='Назва файлу 5'),
        ),
    ]
