# Generated by Django 3.0 on 2020-02-29 20:12

from django.db import migrations, models
import partners.utilites


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartnersLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('logo', models.ImageField(blank=True, upload_to=partners.utilites.get_timestamp_path_logo_partners, verbose_name='Логотип')),
                ('website', models.URLField(max_length=250)),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('sorting', models.PositiveIntegerField(blank=True, verbose_name='Сортування')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Корисні посилання - Партнери',
                'ordering': ['sorting'],
            },
        ),
    ]
