# Generated by Django 3.0 on 2020-02-29 21:03

import announcement.utilites
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Оголошення')),
                ('description', models.TextField(blank=True, verbose_name='Опис оголошення')),
                ('image', models.ImageField(blank=True, upload_to=announcement.utilites.get_timestamp_path_announcement, verbose_name='Фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('sorting', models.PositiveIntegerField(blank=True, verbose_name='Сортування')),
            ],
            options={
                'verbose_name': 'Оголошення',
                'verbose_name_plural': 'Оголошення',
                'ordering': ['sorting'],
            },
        ),
    ]
