# Generated by Django 3.0 on 2020-03-01 17:50

from django.db import migrations, models
import eventsapp.utilites


class Migration(migrations.Migration):

    dependencies = [
        ('eventsapp', '0002_auto_20200129_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('download_file', models.FileField(blank=True, upload_to=eventsapp.utilites.get_timestamp_path_rozklad_file, verbose_name='Додати файл розкладу')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('sorting', models.PositiveIntegerField(blank=True, verbose_name='Сортування')),
            ],
            options={
                'verbose_name': 'Розклад уроків',
                'verbose_name_plural': 'Розклади уроків',
                'ordering': ['sorting'],
            },
        ),
    ]
