# Generated by Django 3.0 on 2020-01-04 23:07

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.utilites


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photologue', '0011_auto_20190223_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleToImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.utilites.get_timestamp_path_article_photo, verbose_name='Загальне Зображення')),
            ],
            options={
                'verbose_name': 'Загальне додаткове зображення',
                'verbose_name_plural': 'Загальні додаткові зображення',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Департамент')),
            ],
            options={
                'verbose_name': 'Департамент',
                'verbose_name_plural': 'Департаменти',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Educationlevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Освітньо-кваліфікаційний рівень')),
            ],
            options={
                'verbose_name': 'Освітньо-кваліфікаційний рівень',
                'verbose_name_plural': 'Освітньо-кваліфікаційні рівні',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PravilaPryiomu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('text', models.TextField(blank=True, verbose_name='Опис')),
                ('format_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Опис розширено')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата публікації')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Правила прийому',
                'verbose_name_plural': 'Правила прийому',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Кваліфікаційна категорія')),
            ],
            options={
                'verbose_name': 'Кваліфікаційна категорія',
                'verbose_name_plural': 'Кваліфікаційні категорії',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Найменування рубрики')),
            ],
            options={
                'verbose_name': 'Рубрика',
                'verbose_name_plural': 'Рубрики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255, verbose_name='Прізвище')),
                ('first_name', models.CharField(max_length=255, verbose_name="Ім'я")),
                ('patronymic', models.CharField(blank=True, max_length=255, verbose_name='По батькові')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Посада')),
                ('position_abb', models.CharField(blank=True, max_length=255, verbose_name='Посада скороченно')),
                ('education', models.CharField(blank=True, max_length=255, verbose_name='Освіта')),
                ('specialty', models.CharField(blank=True, max_length=255, verbose_name='Фах')),
                ('experience', models.PositiveIntegerField(blank=True, null=True, verbose_name='Стаж')),
                ('content', models.TextField(blank=True, verbose_name='Резюме')),
                ('methodical_dev', models.TextField(blank=True, verbose_name='Методичнi розробки')),
                ('image', models.ImageField(blank=True, upload_to='staff', verbose_name='Фото співробітника')),
                ('adding_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата додавання')),
                ('sort_staff', models.PositiveIntegerField(blank=True, verbose_name='Сортування')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Department', verbose_name='Департамент')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Educationlevel', verbose_name='Освітньо-кваліфікаційний рівень')),
                ('qualification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Qualification', verbose_name='Кваліфікаційна категорія')),
            ],
            options={
                'verbose_name': 'Працівник',
                'verbose_name_plural': 'Працівники',
                'ordering': ['sort_staff'],
            },
        ),
        migrations.CreateModel(
            name='Metodikfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='materials', verbose_name='Додаткові файли')),
                ('mf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Staff', verbose_name='Оберіть працівника')),
            ],
            options={
                'verbose_name': 'Додатковий файл',
                'verbose_name_plural': 'Додаткові файли',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, verbose_name='Назва новини')),
                ('text', models.TextField(blank=True, verbose_name='Текст новини')),
                ('article_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Стаття розширена')),
                ('image', models.ImageField(blank=True, upload_to=main.utilites.get_timestamp_path_article, verbose_name='Зображення статті')),
                ('is_image_default', models.BooleanField(default=False, verbose_name='Стандартне зображення')),
                ('is_video_news', models.BooleanField(default=False, verbose_name='Відео новина')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата публікації')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('add_image', models.ManyToManyField(blank=True, related_name='articles', to='main.ArticleToImage')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='photologue.Gallery', verbose_name='Галерея статті')),
                ('rubric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Rubric', verbose_name='Рубрика')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='main.Tag')),
            ],
            options={
                'verbose_name': 'Стаття',
                'verbose_name_plural': 'Статті',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='AdditionalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.utilites.get_timestamp_path_article_photo, verbose_name='Зображення')),
                ('art_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Article', verbose_name='Новини')),
            ],
            options={
                'verbose_name': 'Додаткове зображення',
                'verbose_name_plural': 'Додаткові зображення',
            },
        ),
    ]
