# Generated by Django 3.0 on 2019-12-07 23:35

from django.db import migrations, models
import django.db.models.deletion
import main.utilites


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Департамент')),
            ],
            options={
                'verbose_name': 'Департамент',
                'verbose_name_plural': 'Департаменти',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Educationlevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Освітньо-кваліфікаційний рівень')),
            ],
            options={
                'verbose_name': 'Освітньо-кваліфікаційний рівень',
                'verbose_name_plural': 'Освітньо-кваліфікаційні рівні',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Кваліфікаційна категорія')),
            ],
            options={
                'verbose_name': 'Кваліфікаційна категорія',
                'verbose_name_plural': 'Кваліфікаційні категорії',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Прізвище')),
                ('first_name', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('patronymic', models.CharField(blank=True, max_length=50, verbose_name='По батькові')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Посада')),
                ('education', models.CharField(blank=True, max_length=100, verbose_name='Освіта')),
                ('specialty', models.CharField(blank=True, max_length=50, verbose_name='Фах')),
                ('experience', models.PositiveIntegerField(blank=True, verbose_name='Стаж')),
                ('content', models.TextField(blank=True, verbose_name='Резюме')),
                ('methodical_dev', models.TextField(blank=True, verbose_name='Методичнi розробки')),
                ('image', models.ImageField(blank=True, upload_to=main.utilites.get_timestamp_path, verbose_name='Фото співробітника')),
                ('adding_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата додавання')),
                ('sort_staff', models.PositiveIntegerField(blank=True, verbose_name='Сортування')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Department', verbose_name='Департамент')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Educationlevel', verbose_name='Освітньо-кваліфікаційний рівень')),
                ('qualification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Qualification', verbose_name='Кваліфікаційна категорія')),
            ],
            options={
                'verbose_name': 'Працівник',
                'verbose_name_plural': 'Працівники',
                'ordering': ['sort_staff'],
            },
        ),
        migrations.CreateModel(
            name='Metodikfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='materials', verbose_name='Додаткові файли')),
                ('mf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Staff', verbose_name='Оберіть файл')),
            ],
            options={
                'verbose_name': 'Додатковий файл',
                'verbose_name_plural': 'Додаткові файли',
            },
        ),
    ]
