# Generated by Django 3.0 on 2019-12-07 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.ImageField(blank=True, upload_to='staff', verbose_name='Фото співробітника'),
        ),
    ]
