# Generated by Django 3.0 on 2020-01-13 16:11

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import main.utilites


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZvitDirector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zvit_title', models.TextField(blank=True, verbose_name='Назва Звіту')),
                ('zvit_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Текст Звіту')),
                ('zvit_image', models.ImageField(blank=True, upload_to=main.utilites.get_timestamp_path_article, verbose_name='Зображення Звіту')),
            ],
            options={
                'verbose_name': 'Звіт Директора',
                'verbose_name_plural': 'Звіти Директора',
            },
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='materials', verbose_name='Файл Звіту')),
                ('up_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ZvitDirector', verbose_name='Оберіть Звіт')),
            ],
            options={
                'verbose_name': 'Файл Звіту',
                'verbose_name_plural': 'Файли Звіту',
            },
        ),
    ]
