# Generated by Django 3.0 on 2019-12-08 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191208_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='position_abb',
            field=models.CharField(blank=True, max_length=50, verbose_name='Посада скороченно'),
        ),
    ]
