# Generated by Django 3.0 on 2020-01-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_uploadfile_zvitdirector'),
    ]

    operations = [
        migrations.AddField(
            model_name='zvitdirector',
            name='zvit_active',
            field=models.BooleanField(default=True, verbose_name='Опубліковано'),
        ),
    ]
