# Generated by Django 3.0 on 2019-12-08 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_staff_position_abb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='experience',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Стаж'),
        ),
    ]
