# Generated by Django 3.0 on 2020-01-13 17:51

from django.db import migrations, models
import main.utilites


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_zvitdirector_zvit_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='pravilapryiomu',
            name='file',
            field=models.FileField(blank=True, upload_to='materials', verbose_name='Файл Правил'),
        ),
        migrations.AddField(
            model_name='pravilapryiomu',
            name='image',
            field=models.ImageField(blank=True, upload_to=main.utilites.get_timestamp_path_article, verbose_name='Зображення Правил'),
        ),
    ]
