# Generated by Django 3.0 on 2020-01-17 15:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.utilites


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200113_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodPlans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='План роботи на місяць')),
            ],
            options={
                'verbose_name': 'План',
                'verbose_name_plural': 'Плани',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlanRoboty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='План роботи')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, upload_to=main.utilites.get_timestamp_path_article, verbose_name='Зображення')),
                ('is_image_default', models.BooleanField(default=False, verbose_name='Стандартне зображення')),
                ('file', models.FileField(upload_to='plans', verbose_name='Плани роботи')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата публікації')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активний план')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.PeriodPlans', verbose_name='Період планів')),
            ],
            options={
                'verbose_name': 'План',
                'verbose_name_plural': 'Плани',
                'ordering': ['-published_date'],
            },
        ),
    ]
