# Generated by Django 3.0 on 2020-01-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_periodplans_planroboty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_nimber', models.PositiveIntegerField(blank=True, verbose_name='Позиція в таблиці')),
                ('type_prof', models.CharField(choices=[(None, 'Виберіть тип професії'), ('b', 'первинна професійна підготовка'), ('c', 'професійно-технічне навчання (курсова підготовка)')], max_length=1)),
                ('table_number', models.PositiveIntegerField(blank=True, verbose_name='Номер таблиці')),
                ('code_prof', models.CharField(blank=True, max_length=25, verbose_name='Код професії')),
                ('name_prof', models.CharField(blank=True, max_length=255, verbose_name='Назва професії')),
                ('license_amount', models.PositiveIntegerField(blank=True, verbose_name='Ліцензований обсяг')),
                ('term_of_study_9', models.CharField(blank=True, max_length=50, verbose_name='Термін навчання на базі 9 класів')),
                ('term_of_study_11', models.CharField(blank=True, max_length=50, verbose_name='Термін навчання на базі 11 класів')),
            ],
            options={
                'verbose_name': 'Професії',
                'verbose_name_plural': 'Професія',
                'ordering': ['position_nimber'],
            },
        ),
        migrations.AlterModelOptions(
            name='periodplans',
            options={'ordering': ['-name'], 'verbose_name': 'Період Плану', 'verbose_name_plural': 'Період планів'},
        ),
        migrations.AlterModelOptions(
            name='planroboty',
            options={'ordering': ['-published_date'], 'verbose_name': 'План роботи', 'verbose_name_plural': 'Плани роботи'},
        ),
        migrations.AlterField(
            model_name='periodplans',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='План роботи за:'),
        ),
    ]
