# Generated by Django 3.0 on 2019-12-08 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_article_rubric_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
    ]
