# Generated by Django 3.0 on 2019-12-09 21:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_article_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_date'], 'verbose_name': 'Стаття', 'verbose_name_plural': 'Статті'},
        ),
        migrations.AddField(
            model_name='article',
            name='article_text',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Стаття розширена'),
        ),
    ]
