# Generated by Django 3.0 on 2020-01-27 20:55

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.utilites


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0011_auto_20190223_2138'),
        ('main', '0006_auto_20200117_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Найменування НЦ')),
                ('tc_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Опис НЦ')),
                ('image', models.ImageField(blank=True, upload_to=main.utilites.get_timestamp_path_article, verbose_name='Зображення НЦ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('tc_sort', models.PositiveIntegerField(blank=True, verbose_name='Сортування')),
            ],
            options={
                'verbose_name': 'Навчальний центр',
                'verbose_name_plural': 'Навчальні центри',
                'ordering': ['tc_sort'],
            },
        ),
        migrations.CreateModel(
            name='ResourcesCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, verbose_name='Назва ресурсу')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Опис ресурсу')),
                ('image', models.ImageField(blank=True, upload_to=main.utilites.get_timestamp_path_article, verbose_name='Зображення ресурсу')),
                ('is_image_default', models.BooleanField(default=False, verbose_name='Стандартне зображення')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='photologue.Gallery', verbose_name='Галерея статті')),
                ('training_center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.TrainingCenter', verbose_name='Навчальний центр')),
            ],
            options={
                'verbose_name': 'Ресурс',
                'verbose_name_plural': 'Ресурси',
                'ordering': ['-created_date'],
            },
        ),
    ]
