# Generated by Django 3.0 on 2019-12-29 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20191226_0143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pravilapryiomu',
            options={'ordering': ['-published_date'], 'verbose_name': 'Правила прийому', 'verbose_name_plural': 'Правила прийому'},
        ),
        migrations.AlterField(
            model_name='metodikfile',
            name='mf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Staff', verbose_name='Оберіть працівника'),
        ),
    ]
