# Generated by Django 3.0 on 2019-12-31 13:07

from django.db import migrations, models
import django.db.models.deletion
import main.utilites


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20191230_0102'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.utilites.get_timestamp_path_article_photo, verbose_name='Зображення')),
                ('art_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Article', verbose_name='Новини')),
            ],
            options={
                'verbose_name': 'Додаткове зображення',
                'verbose_name_plural': 'Додаткові зображення',
            },
        ),
    ]
