# Generated by Django 3.0 on 2020-02-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200207_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletoimage',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
