# Generated by Django 3.0 on 2019-12-31 13:19

from django.db import migrations, models
import main.utilites


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_additionalimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleToImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.utilites.get_timestamp_path_article_photo, verbose_name='Загальне Зображення')),
            ],
            options={
                'verbose_name': 'Загальне додаткове зображення',
                'verbose_name_plural': 'Загальні додаткові зображення',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='add_image',
            field=models.ManyToManyField(blank=True, related_name='articles', to='main.ArticleToImage'),
        ),
    ]
