# Generated by Django 3.0 on 2020-02-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_articletoimage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalimage',
            name='title',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='articletoimage',
            name='title',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
