# Generated by Django 3.0 on 2019-12-31 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0011_auto_20190223_2138'),
        ('main', '0011_auto_20191231_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='gallery',
            field=models.ManyToManyField(blank=True, to='photologue.Gallery'),
        ),
    ]
