# Generated by Django 3.0 on 2020-08-20 13:43

from django.db import migrations, models
import main.utilites


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200220_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navchild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='Найменування пункту меню')),
                ('position_number', models.PositiveIntegerField(blank=True, verbose_name='Позиція у меню')),
                ('file', models.FileField(blank=True, upload_to=main.utilites.get_timestamp_path_navmenu, verbose_name='Файл до меню')),
            ],
            options={
                'verbose_name': 'Пункт дочірнього меню',
                'verbose_name_plural': 'Пункти дочірнього меню',
                'ordering': ['position_number'],
            },
        ),
        migrations.CreateModel(
            name='Navmenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, verbose_name='Назва меню')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('position_number', models.PositiveIntegerField(blank=True, verbose_name='Позиція меню')),
                ('navchild', models.ManyToManyField(blank=True, related_name='navmenu', to='main.Navchild')),
            ],
            options={
                'verbose_name': 'Загальне Меню',
                'verbose_name_plural': 'Загальне Меню',
                'ordering': ['position_number'],
            },
        ),
    ]
