# Generated by Django 3.0 on 2019-12-31 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_article_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='gallery',
        ),
    ]
