# Generated by Django 3.0 on 2020-08-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_navchild_navmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='navchild',
            name='navchild_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Посилання для меню'),
        ),
        migrations.AddField(
            model_name='navmenu',
            name='navmenu_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Посилання для меню'),
        ),
    ]
