# Generated by Django 3.0 on 2020-08-20 13:51

from django.db import migrations, models
import main.utilites


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200820_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='navmenu',
            name='file_menu',
            field=models.FileField(blank=True, upload_to=main.utilites.get_timestamp_path_navmenu, verbose_name='Файл до меню'),
        ),
    ]
