# Generated by Django 3.0 on 2019-12-31 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0011_auto_20190223_2138'),
        ('main', '0013_remove_article_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='photologue.Gallery', verbose_name='Галерея статті'),
        ),
    ]
