# Generated by Django 3.0 on 2020-08-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_navmenu_file_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='navchild',
            name='is_file_active',
            field=models.BooleanField(default=False, verbose_name='Активне посилання на файл'),
        ),
        migrations.AddField(
            model_name='navchild',
            name='is_url_active',
            field=models.BooleanField(default=False, verbose_name='Активне посилання'),
        ),
        migrations.AddField(
            model_name='navmenu',
            name='is_file_active',
            field=models.BooleanField(default=False, verbose_name='Активне посилання на файл'),
        ),
        migrations.AddField(
            model_name='navmenu',
            name='is_url_active',
            field=models.BooleanField(default=False, verbose_name='Активне посилання'),
        ),
    ]
