# Generated by Django 3.0 on 2019-12-31 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_article_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_image_default',
            field=models.BooleanField(default=False, verbose_name='Стандартне зображення'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Опубліковано'),
        ),
    ]
