# Generated by Django 3.0 on 2020-08-23 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200820_1848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navchild',
            options={'ordering': ['title'], 'verbose_name': 'Пункт дочірнього меню', 'verbose_name_plural': 'Пункти дочірнього меню'},
        ),
    ]
