# Generated by Django 3.0 on 2020-01-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20191231_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_video_news',
            field=models.BooleanField(default=False, verbose_name='Відео новина'),
        ),
    ]
