# Generated by Django 3.0 on 2020-08-23 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0001_initial'),
        ('main', '0016_auto_20200823_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='navchild',
            name='child_content',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitecontent.Content', verbose_name='Наповнення рубріки'),
        ),
        migrations.AddField(
            model_name='navmenu',
            name='menu_content',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitecontent.Content', verbose_name='Наповнення'),
        ),
    ]
