# Generated by Django 3.0 on 2020-01-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200104_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pravilapryiomu',
            name='text',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='pravilapryiomu',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Назва'),
        ),
    ]
