# Generated by Django 3.0 on 2020-01-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200104_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(blank=True, verbose_name='Назва новини, максимально - 250'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Департамент'),
        ),
        migrations.AlterField(
            model_name='educationlevel',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Освітньо-кваліфікаційний рівень'),
        ),
        migrations.AlterField(
            model_name='metodikfile',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pravilapryiomu',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Кваліфікаційна категорія'),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Найменування рубрики'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='education',
            field=models.CharField(blank=True, max_length=255, verbose_name='Освіта'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='staff',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='patronymic',
            field=models.CharField(blank=True, max_length=255, verbose_name='По батькові'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(blank=True, max_length=255, verbose_name='Посада'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position_abb',
            field=models.CharField(blank=True, max_length=255, verbose_name='Посада скороченно'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='specialty',
            field=models.CharField(blank=True, max_length=255, verbose_name='Фах'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
